### ISSUE TITLE
How do I indent using the tab key?

### ISSUE THREAD

**Issue by dydx-git** [christianheine/prosemirror-svelte#2]
Lets say I'd like to add / indent 4 spaces when I press tab. Here however, when pressing tab it takes the focus out of the component.

**Comment by christianheine** [comment]
Well, it's more a Prosemirror thing. 

I think the best option would be to create Prosemirror plugin which handles the keypress. If you return false from here, you can implement your own logic.

```
new Plugin({
   // ...
    props: {
      handleKeyDown(view, event): boolean {
        const {doc, selection} = view.state;
          if (options.tabulator && event.key === "Tab") {
            // your code here
            return true;
        }
        return false;
      }
```

More on plugins: https://prosemirror.net/docs/ref/#state.Plugin_System

Another great resource for anything related to prosemirror: https://discuss.prosemirror.net/
