### ISSUE TITLE
Disable pasting images to text

### ISSUE THREAD

**Issue by gomeslucasm** [christianheine/prosemirror-svelte#6]
I want some way to disable the ability for users to paste images into text due to the issue of pasting images that will be converted to base64 at pasting time.

I have two possibilities to solve:

- Disable image paste for any type of file.
- Disable pasting of images that are base64. 

ps: images are being added to the text with CTRL+V, not using the ```insertImage``` helper.

**Comment by christianheine** [comment]
The most straightforward way to handle this would probably be using the [handlePaste prop of the underlying EditorView](https://prosemirror.net/docs/ref/#view.EditorProps.handlePaste). I've just added this tentatively as an additional prop to the EditorView. The only caveat is that it's set on mount, so if you change these props later, it would not be propagated. 

Here's how this could be used called. The third parameter of handlePaste would be the [Slice](https://prosemirror.net/docs/ref/#model.Slice) of content to be added. If that's an image you could return false. Or you directly use the raw event. 

```Svelte
<ProsemirrorEditor
  {editorState}
  editorViewProps={{handlePaste: (...a) => {console.log(a)}}}
  bind:focus={focusEditor}
  on:change={handleChange}
  placeholder="Go ahead and edit me!"/>
```

**Comment by gomeslucasm** [comment]
Thanks for the answer @christianheine.

Could you tell me if the npm package is up to date? I did the installation via yarn and the ```ProsemirrorEditor``` component is not receiving the ```editorViewProps``` props. I installed the version ```"^0.2.3"```.

**Comment by christianheine** [comment]
I had only updated the repo so far. The npm package is now also updated to 0.2.4.
